version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - "3307:3306"  # Porta externa:interna
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: ["/wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    working_dir: /app
    entrypoint: ["/wait-for-it.sh", "db:3306", "--"]

volumes:
  db_data:
